services:
  postgres:
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=data_pumpster'
      - 'POSTGRES_USER=data_pumpster'
      - 'POSTGRES_PASSWORD=data_pumpster'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U data_pumpster -d data_pumpster']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
